[book]
authors = ["andrew"]
language = "en"
multilingual = false
src = "src"
title = "rv2-presentation"

[output.html]
additional-css = ["mdbook_plugin/visualization.css"]
additional-js = ["mdbook_plugin/helpers.js", "mdbook_plugin/book.js"]